### PR TITLE
chore(bolt-sidecar): fix lints

### PR DESCRIPTION
**Pull request by estensen**
Ran `cargo clippy` locally and CI is running `cargo clippy --all-targets --all-features -- -D warnings`

### CODE REVIEW

**Comment by merklefruit** [comment]
It would be nice to add quick recipes for linting in the justfile, something like

```just
clippy package:
	cd {{ package }} && cargo clippy --all-targets --all-features -- -D warnings
```

so we can do `just clippy bolt-sidecar`

**Comment by estensen** [comment]
> It would be nice to add quick recipes for linting in the justfile, something like
> 
> ```just
> clippy package:
> 	cd {{ package }} && cargo clippy --all-targets --all-features -- -D warnings
> ```
> 
> so we can do `just clippy bolt-sidecar`

Great idea!
https://github.com/chainbound/bolt/pull/436

**Comment by mempirate** [comment]
@estensen @merklefruit you could even install this in a pre-commit hook

**Comment by estensen** [comment]
> @estensen @merklefruit you could even install this in a pre-commit hook

yes, but let's improve it one commit at a time

**Comment by merklefruit** [comment]
> pre-commit hook

My personal opinion is that CI >>> pre-commit hooks. 
I would greatly appreciate if we don't add any hooks to slow down our workflow

**Comment by estensen** [comment]
Not sure why I'm not able to repro failures locally

`rustc 1.82.0 (f6e511eec 2024-10-15)`

**Comment by merklefruit** [comment]
> Not sure why I'm not able to repro failures locally
> 
> `rustc 1.82.0 (f6e511eec 2024-10-15)`

same

**Review by thedevbirb — APPROVED** [review]

**Pull request merged**
