### PR TITLE
chore(bolt-boost): add more lints

### PR DESCRIPTION
**Pull request by estensen**
Please protest if you disagree and I'll avoid adding until we have reached agreement 🤝

### CODE REVIEW

**Review by mempirate — APPROVED** [review]
I like it. We should turn this into a template for Chainbound Rust projects along with other defaults (formatters, toolchains, CI). Edit: could we also add this for the bolt-sidecar

**Comment by mempirate** [comment]
Could you also do a PR for bolt?

**Comment by estensen** [comment]
> I like it. We should turn this into a template for Chainbound Rust projects along with other defaults (formatters, toolchains, CI). Edit: could we also add this for the bolt-sidecar

Not sure what the best-practice for Rust monorepos to share tooling like linting is. I'll just copy it for now to bolt-sidecar and bolt-cli.

**Review by thedevbirb — APPROVED** [review]
AFAIK all clippy lints try to enforce either readability, idiomatic Rust, performance and possible footguns. All good stuff. Feel free to add them! We can eventually consider removing them at a later stage if we find some annoying ones.

**Pull request merged**
